{
 "title": "APPLICATION API DASHBOARD",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Application Boot Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_started_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(http_request_total) by (method, path, status))\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(increase(http_request_total{status=~\"4.*|5.*\", job=\"$job\"}[$__range]))\r\n  /\r\n  sum(increase(http_request_total{job=\"$job\"}[$__range]))\r\n)\r\nor vector(0)\r\n"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[$__range]))/sum(rate(http_request_duration_seconds_count[$__range]))"
    }
   ]
  },
  {
   "title": "Request In Progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_in_progress)" }
   ]
  },
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "API Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(http_request_total{job=\"$job\"}[$__range])\r\n",
     "legendFormat": "{{method}} {{path}}{{status}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Request By Status  Code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_total{job=\"$job\"}[$__range])) by (status)\r\n",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Average Duration Of Request",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "(rate(http_request_duration_seconds_sum[1m]))/(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{method}}{{path}}{{status}}"
    }
   ]
  },
  {
   "title": "API Latency Percentile",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket[5m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket[5m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[5m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket[5m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}